In [1]:
import pandas as pd
import numpy as np
import operator
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report

#讀檔
f = open('training_label.txt', mode='r', encoding='utf-8')
f2 = open('testing_label.txt', mode='r', encoding='utf-8')

x = []
train = []
test = []

#train傳換為list(2維)，且只取前10000筆
for line in f:
     x.append(line.strip('\n'))
for i in range(10000):
    train.append(x[i].split(' +++$+++ '))

#test傳換為list(2維)    
for line in f2:
    if line == '\n':
        continue
    test.append(line.strip('\n').split('#####'))
    
#以下為list的降維：
#list轉str
temp1 = str(train)
#替換'[' ']'
temp1 = temp1.replace('[','')
temp1 = temp1.replace(']','')
#轉list
train = list(eval(temp1))

#test同上
temp2 = str(test)
temp2 = temp2.replace('[','')
temp2 = temp2.replace(']','')
test = list(eval(temp2))


In [2]:
#將train的label與data分成2 list
train_emotion = []
train_words = []
for i in range(20000):
    if (i%2 == 0):
        train_emotion.append(train[i])
    else:
        train_words.append(train[i])
#Dataframe
df_train = pd.DataFrame(list(zip(train_emotion, train_words)), columns =['emotion', 'words'])
df_train

emotion                                              words
0          1                          are wtf ... awww thanks !
1          1  leavingg to wait for kaysie to arrive myspacin...
2          0  i wish i could go and see duffy when she comes...
3          1  i know eep ! i can ' t wait for one more day ....
4          0  so scared and feeling sick . fuck ! hope someo...
...      ...                                                ...
9995       0  i know the feeling !! but don ' t be hun ! eve...
9996       1  i was just asked today if i was a conservative...
9997       0  cubs white soxs game rained out ... of all nig...
9998       1            props to your mom she did a great job !
9999       0                                  ooo sorry to hear

[10000 rows x 2 columns]

In [3]:
#將test的label與data分成2 list
test_emotion = []
test_words = []
for i in range(180):
    if (i%2 == 0):
        test_emotion.append(test[i])
    else:
        test_words.append(test[i])
#Dataframe        
df_test = pd.DataFrame(list(zip(test_emotion, test_words)), columns =['emotion', 'words'])
df_test

emotion                                              words
0        0  don ' t you hate it when you hang on to a seem...
1        0  ok so never went to the movies because friend ...
2        1    can ' t wait to see diversity ' s performance !
3        1  i love britney spears haha joey this is what u...
4        1                                       1 more day !
..     ...                                                ...
85       1  shower time !!! then more shopping for my new ...
86       1  awwwwww too cute ! makes me miss my westie bac...
87       0          thanks . lol . sadly i am 31 !! waaahhhhh
88       1  thanks ! i am listening to her on lala . com r...
89       0  monday ! whoo hooo ! why am i so excited ? mig...

[90 rows x 2 columns]

In [4]:
#去除停用字，停用字庫網路搜尋而得
words = train_words+test_words
stopwords=["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now", "ah", "20", "5977", "0347", "18", "any", "70"]
cv = CountVectorizer(stop_words=stopwords) #將文字中的詞語轉換為詞頻矩陣 
x_train = cv.fit_transform(words) #計算個詞語出現的次數
print(x_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
#將詞頻矩陣統計成TF-IDF值 
transformer = TfidfTransformer()  
x_tfidf = transformer.fit_transform(x_train)   
x_tfidf = x_tfidf.toarray()
x_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
#合併train與test的label成為一個list y
y = train_emotion + test_emotion
y = np.array(y)

In [7]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation,Flatten
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM

Using TensorFlow backend.


In [8]:
model = Sequential()

In [9]:
model.add(Embedding(output_dim=32,
                    input_dim=3800, 
                    input_length=13444))
model.add(Dropout(0.7))




Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [10]:
model.add(LSTM(32))

In [11]:
model.add(Dense(units=256,
                activation='relu' ))
model.add(Dropout(0.7))

In [12]:
model.add(Dense(units=1,
                activation='sigmoid' ))

In [13]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 13444, 32)         121600    
_________________________________________________________________
dropout_1 (Dropout)          (None, 13444, 32)         0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_1 (Dense)              (None, 256)               8448      
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 257       
Total params: 138,625
Trainable params: 138,625
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss='binary_crossentropy', 
              #optimizer='rmsprop', 
              optimizer='adam', 
              metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [15]:
train_history =model.fit(x_tfidf, y,batch_size=100, 
                         epochs=10,verbose=2,
                         validation_split=0.2)




Train on 8072 samples, validate on 2018 samples
Epoch 1/10







ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-b6af4ca794d1>", line 3, in <module>
    validation_split=0.2)
  File "C:\Users\user\Anaconda3\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\user\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.f

InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(100, 32), b.shape=(32, 32), m=100, n=32, k=32
	 [[{{node lstm_1/while/MatMul_4}}]]
	 [[loss/mul/_113]]
  (1) Internal: Blas GEMM launch failed : a.shape=(100, 32), b.shape=(32, 32), m=100, n=32, k=32
	 [[{{node lstm_1/while/MatMul_4}}]]
0 successful operations.
0 derived errors ignored.

In [ ]:
%pylab inline
import matplotlib.pyplot as plt
def show_train_history(train_history,train,validation):
    plt.plot(train_history.history[train])
    plt.plot(train_history.history[validation])
    plt.title('Train History')
    plt.ylabel(train)
    plt.xlabel('Epoch')
    plt.legend(['train', 'validation'], loc='upper left')
    plt.show()

In [ ]:
show_train_history(train_history,'acc','val_acc')

In [ ]:
show_train_history(train_history,'loss','val_loss')

In [ ]:
scores = model.evaluate(x_tfidf[10000:10090], df_test['emotion'], verbose=1)
scores[1]